"""Shared data contracts for God's Eye."""

from godseye.schemas.enums import (
    PROVENANCE_TO_CONFIDENCE,
    ArtifactKind,
    ConfidenceTier,
    ExecutionTarget,
    FailureOrigin,
    JobStatus,
    PipelineMode,
    Provenance,
    StageName,
    StageStatus,
)
from godseye.schemas.manifest import (
    ArtifactRecord,
    JobManifest,
    StageError,
    StageRecord,
    VideoMetadata,
    utcnow,
)
from godseye.schemas.remote import (
    GeometryRequest,
    ReconstructionRequest,
    RemoteArtifact,
    RemoteError,
    RemoteStageResult,
)
from godseye.schemas.scene import (
    BoundingBox,
    ConfidenceDocument,
    ConfidenceRegion,
    GeometrySummary,
    ObjectsDocument,
    RunSummaryDocument,
    SceneDocument,
    SceneGraphDocument,
    SceneGraphEdge,
    SceneGraphNode,
    SceneObject,
    StageSummary,
    Transform,
    Vec3,
)

__all__ = [
    "PROVENANCE_TO_CONFIDENCE",
    "ArtifactKind",
    "ArtifactRecord",
    "BoundingBox",
    "ConfidenceDocument",
    "ConfidenceRegion",
    "ConfidenceTier",
    "ExecutionTarget",
    "FailureOrigin",
    "GeometryRequest",
    "GeometrySummary",
    "JobManifest",
    "JobStatus",
    "ObjectsDocument",
    "PipelineMode",
    "Provenance",
    "ReconstructionRequest",
    "RemoteArtifact",
    "RemoteError",
    "RemoteStageResult",
    "RunSummaryDocument",
    "SceneDocument",
    "SceneGraphDocument",
    "SceneGraphEdge",
    "SceneGraphNode",
    "SceneObject",
    "StageError",
    "StageName",
    "StageRecord",
    "StageStatus",
    "StageSummary",
    "Transform",
    "Vec3",
    "VideoMetadata",
    "utcnow",
]
